appName: currencyservice
appReplicas: 2
appImage: gcr.io/google-samples/microservices-demo/currencyservice
appVersion: v0.2.3
containerPort: 7000
containerEnvVar:
- name: PORT
  value: "7000"
servicePort: 7000
serviceType: ClusterIP