appName: recommendationservice
appReplicas: 2
appImage: gcr.io/google-samples/microservices-demo/recommendationservice
appVersion: v0.2.3
containerPort: 8080
containerEnvVar:
- name: PORT
  value: "8080"
- name: PRODUCT_CATALOG_SERVICE_ADDR
  value: "productcatalogservice:3550"
- name: DISABLE_TRACING
  value: "1"
- name: DISABLE_PROFILER
  value: "1"
servicePort: 8080
serviceType: ClusterIP